Repository jiyxxn/react-chillpedia, pull requests merged in 2025-02, with the labels that each got.

#2 📄 Docs : 이슈 템플릿 수정
  .github/ISSUE_TEMPLATE/feature-template.md
Labels: 📃 Docs

#4 [Share] 공용 파일 수정
  src/components/FoodCategoryTag.jsx
  src/index.css
Labels: ✨ Feature, 🎨 Html&css

#5 [Styling] Global Styles 적용
  index.html
  src/App.css
  src/App.jsx
  src/index.css
  src/main.jsx
  src/styles/globalStyles.js
Labels: 🎨 Html&css

#7 [Chore] prettier 경로 오류 수정
  .eslintignore
  .prettierignore
  package.json
  pnpm-lock.yaml
  src/styles/reset.css
Labels: ⚙ Chore

#13 Feat/make detail page
  README.md
  src/components/PostCommentArea.jsx
  src/components/PostDetailCard.jsx
  src/pages/PostDetail.jsx
  src/styles/detailCard.styled.js
  src/styles/globalStyles.js
Labels: ✨ Feature

#14 Feat/make signup page
  package.json
  pnpm-lock.yaml
  src/App.jsx
  src/components/PostCommentArea.jsx
  src/components/SignupForm.jsx
  src/components/ToastAlert.jsx
  src/pages/Signup.jsx
  src/shared/Router.jsx
  src/styles/Signup.styled.js
Labels: ✨ Feature, 🎨 Html&css

#21 Feat/make login page
  public/chill_logo.png
  public/icon_login.png
  public/icon_logout.png
  public/icon_mypage.png
  src/components/LayoutHeader.jsx
  src/pages/Login.jsx
  src/pages/Mypage.jsx
  src/providers/AuthProvider.jsx
  src/shared/Router.jsx
Labels: ✨ Feature

#18 Refactor/#17 게시글 상세페이지 리팩토링
  src/components/PostCommentArea.jsx
  src/components/PostCommentCard.jsx
  src/components/PostDetailCard.jsx
  src/pages/PostDetail.jsx
Labels: 🔨 Refactor

#20 Feat/make my page
  public/profile_default.png
  src/components/MyPostList.jsx
  src/components/MyProfile.jsx
  src/components/PostPreviewCard.jsx
  src/pages/Mypage.jsx
  src/pages/Signup.jsx
  src/styles/myPage.styled.js
  src/utils/formatDate.js
  src/utils/userDataValidations.js
Labels: ✨ Feature, 🎨 Html&css

#22 🎨 Style: css완료
  public/icon_select_down.png
  src/components/HandleSelectBox.jsx
  src/pages/PostWrite.jsx
  src/shared/Category.js
  src/shared/locationList.js
Labels: 🎨 Html&css

#24 feat/make list page
  pnpm-lock.yaml
  src/components/FoodCategoryTag.jsx
  src/components/PostCommentArea.jsx
  src/components/PostDetailCard.jsx
  src/components/PostList.jsx
  src/pages/PostDetail.jsx
  src/shared/supabaseClient.js
  vscode/settings.json
Labels: 🎨 Html&css

#25 Refactor/login page
  src/components/LayoutHeader.jsx
  src/pages/Login.jsx
  src/providers/AuthProvider.jsx
Labels: 🎨 Html&css, 🔨 Refactor

#27 Refactor/전체 파일 세부 수정
  src/components/PostCommentCard.jsx
  src/components/PostList.jsx
  src/pages/PostWrite.jsx
  src/styles/detailCard.styled.js
Labels: 🔨 Refactor

#29 refactor/게시글 눌렀을 때 페이지 이동
  src/components/MyPostList.jsx
  src/styles/myPage.styled.js
Labels: ✨ Feature

#30 🩹 Fix: 게시글 수정 버튼 클릭 시 수정됨
  src/pages/PostWrite.jsx
  src/shared/Router.jsx
Labels: 🔨 Refactor

#32 Fix upload image
  src/App.jsx
  src/pages/PostWrite.jsx
  src/providers/UserProfilesProvider.jsx
  src/styles/detailCard.styled.js
Labels: 🔨 Refactor, ✅ Test

#36 📄 Docs : README 작성
  README.md
Labels: 📃 Docs

#39 changed to toastify
  src/components/MyPostList.jsx
  src/components/MyProfile.jsx
  src/pages/PostWrite.jsx
  src/pages/Signup.jsx
Labels: 🧹 CleanUp, 🎨 Html&css

#40 🎉 Add: verce json file
  src/components/LayoutHeader.jsx
  vercel.json
Labels: 🌏 Deploy
